#!/usr/bin/env node
require('source-map-support').install();

const {State, Random} = require('./build');

const state = State.create(process.argv[2] ? new Random(Random.seed(+process.argv[2])) : new Random());
if (process.env.DEBUG) console.debug(state, state.hand.slice().sort().join(''));
const result = state.search(1e7, false);
if (!result.path) {
  console.error(`Unsuccessfully searched ${result.visited} states`);
  process.exit(1);
} else {
  console.log(`Found a path of length ${result.path.length} after searching ${result.visited} states:\n${State.display(result.path, result.trace)}`);
}
