#!/usr/bin/env node
require('source-map-support').install();

const {State, Random, search, bulb} = require('./build');

const cutoff = 1e7;
const prescient = true;

let state = State.create(process.argv[2] ? new Random(Random.seed(+process.argv[2])) : new Random());
const r1 = search({key: state.toString(), state, score: state.score()}, cutoff, prescient);
console.log(r1.visited, r1.path?.length);

state = State.create(process.argv[2] ? new Random(Random.seed(+process.argv[2])) : new Random());
const r2 = bulb({key: state.toString(), state, score: state.score()}, +process.argv[3] || 5, cutoff, prescient);
console.log(r2.visited, r2.path?.length);
